# SPDX-License-Identifier: GPL-2.0-or-later

include(FindPackageHandleStandardArgs)

set(_ONNXRUNTIME_HINTS)
foreach(_ONNXRUNTIME_ROOT_VAR IN ITEMS ONNXRUNTIME_ROOT ONNXRuntime_ROOT)
  if(DEFINED ${_ONNXRUNTIME_ROOT_VAR})
    list(APPEND _ONNXRUNTIME_HINTS "${${_ONNXRUNTIME_ROOT_VAR}}")
  endif()
endforeach()
if(DEFINED ENV{ONNXRUNTIME_ROOT})
  list(APPEND _ONNXRUNTIME_HINTS "$ENV{ONNXRUNTIME_ROOT}")
endif()
if(DEFINED ENV{ONNXRuntime_ROOT})
  list(APPEND _ONNXRUNTIME_HINTS "$ENV{ONNXRuntime_ROOT}")
endif()

find_path(ONNXRUNTIME_INCLUDE_DIR
  NAMES onnxruntime_cxx_api.h
  HINTS ${_ONNXRUNTIME_HINTS}
  PATH_SUFFIXES include include/onnxruntime/core/session
)

find_library(ONNXRUNTIME_LIBRARY
  NAMES onnxruntime libonnxruntime
  HINTS ${_ONNXRUNTIME_HINTS}
  PATH_SUFFIXES lib lib64
)

find_file(ONNXRUNTIME_RUNTIME_LIBRARY
  NAMES onnxruntime.dll libonnxruntime.so libonnxruntime.dylib
  HINTS ${_ONNXRUNTIME_HINTS}
  PATH_SUFFIXES bin lib lib64
)

set(_ONNXRUNTIME_RUNTIME_HINTS ${_ONNXRUNTIME_HINTS})
if(ONNXRUNTIME_RUNTIME_LIBRARY)
  get_filename_component(_ONNXRUNTIME_RUNTIME_DIR "${ONNXRUNTIME_RUNTIME_LIBRARY}" DIRECTORY)
  list(PREPEND _ONNXRUNTIME_RUNTIME_HINTS "${_ONNXRUNTIME_RUNTIME_DIR}")
endif()

find_file(ONNXRUNTIME_PROVIDERS_SHARED_LIBRARY
  NAMES onnxruntime_providers_shared.dll libonnxruntime_providers_shared.so libonnxruntime_providers_shared.dylib
  HINTS ${_ONNXRUNTIME_RUNTIME_HINTS}
  PATH_SUFFIXES bin lib lib64
)

set(_ONNXRUNTIME_REQUIRED_VARS ONNXRUNTIME_INCLUDE_DIR ONNXRUNTIME_LIBRARY)
if(WIN32)
  list(APPEND _ONNXRUNTIME_REQUIRED_VARS ONNXRUNTIME_RUNTIME_LIBRARY)
endif()

find_package_handle_standard_args(ONNXRuntime
  REQUIRED_VARS ${_ONNXRUNTIME_REQUIRED_VARS}
)

if(ONNXRuntime_FOUND AND NOT TARGET ONNXRuntime::ONNXRuntime)
  if(WIN32 AND ONNXRUNTIME_RUNTIME_LIBRARY)
    add_library(ONNXRuntime::ONNXRuntime SHARED IMPORTED)
    set_target_properties(ONNXRuntime::ONNXRuntime PROPERTIES
      IMPORTED_IMPLIB "${ONNXRUNTIME_LIBRARY}"
      IMPORTED_LOCATION "${ONNXRUNTIME_RUNTIME_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${ONNXRUNTIME_INCLUDE_DIR}"
    )
  else()
    add_library(ONNXRuntime::ONNXRuntime UNKNOWN IMPORTED)
    set_target_properties(ONNXRuntime::ONNXRuntime PROPERTIES
      IMPORTED_LOCATION "${ONNXRUNTIME_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${ONNXRUNTIME_INCLUDE_DIR}"
    )
  endif()
endif()

set(ONNXRUNTIME_RUNTIME_DEPENDENCIES)
if(ONNXRUNTIME_RUNTIME_LIBRARY)
  list(APPEND ONNXRUNTIME_RUNTIME_DEPENDENCIES "${ONNXRUNTIME_RUNTIME_LIBRARY}")
endif()
if(ONNXRUNTIME_PROVIDERS_SHARED_LIBRARY)
  list(APPEND ONNXRUNTIME_RUNTIME_DEPENDENCIES "${ONNXRUNTIME_PROVIDERS_SHARED_LIBRARY}")
endif()

mark_as_advanced(
  ONNXRUNTIME_INCLUDE_DIR
  ONNXRUNTIME_LIBRARY
  ONNXRUNTIME_RUNTIME_LIBRARY
  ONNXRUNTIME_PROVIDERS_SHARED_LIBRARY
)
